### ISSUE TITLE
Panic in chunkreader.go:61

### ISSUE THREAD

**Issue by levdikpavel** [jackc/pgx#1155]
Hi, jackc.

We have a high load application. After upgrading from pgx/v4 4.13.0 to pgx/v4 4.14.0 we started to get panic. It reproduces only in high load and low probability. 

Stack trace is below
`panic: runtime error: slice bounds out of range [1629:1625]

goroutine 3558588163 [running]:
panic({0xe42dc0, 0xc0634369c0})
	/-S/contrib/go/_std/src/runtime/panic.go:1147 +0x3a8 fp=0xc0082b1978 sp=0xc0082b18b8 pc=0x28658e8
runtime.goPanicSliceB(0x65d, 0x659)
	/-S/contrib/go/_std/src/runtime/panic.go:118 +0x75 fp=0xc0082b19b8 sp=0xc0082b1978 pc=0x2862e35
github.com/jackc/chunkreader/v2.(*ChunkReader).Next(0xc0a8b35a40, 0x5)
	/-S/vendor/github.com/jackc/chunkreader/v2/chunkreader.go:61 +0x365 fp=0xc0082b1a28 sp=0xc0082b19b8 pc=0x2c18a05
github.com/jackc/pgproto3/v2.(*Frontend).Receive(0xc001281800)
	/-S/vendor/github.com/jackc/pgproto3/v2/frontend.go:82 +0x129 fp=0xc0082b1ab8 sp=0xc0082b1a28 pc=0x2c20e49
a.yandex-team.ru/mds/s3/goose/internal/db/postgres/pgcommon.(*frontendPatcher).Receive(0x5)
	/-S/mds/s3/goose/internal/db/postgres/pgcommon/connect.go:105 +0x22 fp=0xc0082b1ad0 sp=0xc0082b1ab8 pc=0x3049842
github.com/jackc/pgconn.(*PgConn).peekMessage(0xc0427762c0)
	/-S/vendor/github.com/jackc/pgconn/pgconn.go:466 +0x136 fp=0xc0082b1b38 sp=0xc0082b1ad0 pc=0x2c673f6
github.com/jackc/pgconn.(*PgConn).receiveMessage(0xc0427762c0)
	/-S/vendor/github.com/jackc/pgconn/pgconn.go:486 +0x25 fp=0xc0082b1ba0 sp=0xc0082b1b38 pc=0x2c67505
github.com/jackc/pgconn.(*MultiResultReader).receiveMessage(0xc0427763d8)
	/-S/vendor/github.com/jackc/pgconn/pgconn.go:1306 +0x28 fp=0xc0082b1bf0 sp=0xc0082b1ba0 pc=0x2c6e188
github.com/jackc/pgconn.(*MultiResultReader).NextResult(0xc0427763d8)
	/-S/vendor/github.com/jackc/pgconn/pgconn.go:1331 +0x56 fp=0xc0082b1d18 sp=0xc0082b1bf0 pc=0x2c6e616
github.com/jackc/pgx/v4.(*Conn).Query(0xc062f86100, {0x1339c68, 0xc060db2330}, {0xc049515500, 0x92d}, {0xc0397372c0, 0xc03ef35260, 0xc03ef35260})
	/-S/vendor/github.com/jackc/pgx/v4/conn.go:612 +0x35e fp=0xc0082b1e88 sp=0xc0082b1d18 pc=0x2d23b3e
github.com/jackc/pgx/v4/stdlib.(*Conn).QueryContext(0xc04eb80d80, {0x1339c68, 0xc060db2330}, {0xc049515500, 0x92d}, {0xc078bdb5f0, 0x5, 0x5})
	/-S/vendor/github.com/jackc/pgx/v4/stdlib/sql.go:415 +0x1e5 fp=0xc0082b1f30 sp=0xc0082b1e88 pc=0x3044da5
a.yandex-team.ru/mds/s3/goose/internal/db/postgres/clusters.(*clusterConn).QueryContext.func1()
	/-S/mds/s3/goose/internal/db/postgres/clusters/cluster_connector.go:259 +0xaf fp=0xc0082b1fe0 sp=0xc0082b1f30 pc=0x306e44f
runtime.goexit()
	/-S/contrib/go/_std/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0082b1fe8 sp=0xc0082b1fe0 pc=0x28994c1
created by a.yandex-team.ru/mds/s3/goose/internal/db/postgres/clusters.(*clusterConn).QueryContext
	/-S/mds/s3/goose/internal/db/postgres/clusters/cluster_connector.go:257 +0x2d1
 `

And two extra cases with same stack traces
`panic: runtime error: slice bounds out of range [1337:1334]
panic: runtime error: slice bounds out of range [6998:6995]`

May be this issue is related to https://github.com/jackc/pgx/issues/1138, I don't know.

**Comment by jackc** [comment]
If you are using batches and closing the results twice this is almost certainly the same issue as #1138. Try pgx `v4.15.0`. It now allows batch results to be safely closed multiple times.

**Comment by vitalif** [comment]
We're not :-) we don't use batches... I wonder if it's https://github.com/jackc/pgconn/commit/3bee0c6398156fb4c1c302a0ce7b0b5bd6108ce9 that made the impact. It looks really strange, but it seems there are no other significant differences between 4.13 and 4.14 except this one and batch-related stuff. Maybe that read() was making conn.close() thread-safe in the previous versions...?

**Comment by jackc** [comment]
Hmm. I don't see how https://github.com/jackc/pgconn/commit/3bee0c6398156fb4c1c302a0ce7b0b5bd6108ce9 could be the cause. At that point it should only be closing the `net.Conn` and never be used again.

Also, it appears something is patched in between pgconn and pgproto3.

```
a.yandex-team.ru/mds/s3/goose/internal/db/postgres/pgcommon.(*frontendPatcher).Receive(0x5)
	/-S/mds/s3/goose/internal/db/postgres/pgcommon/connect.go:105 +0x22 fp=0xc0082b1ad0 sp=0xc0082b1ab8 pc=0x3049842
```

Not sure what that is.

Any chance of running with the race detector? This is almost certainly a race condition somewhere.

**Comment by levdikpavel** [comment]
frontendPatcher is our wrapper to make SecretKey reset to zero on Receive.

I tried to run our app with race detector, but couldn't catch that race yet. Seems like we should run it under high load, or maybe some extra conditions. Not sure we will achieve success, but we will try.

**Comment by tlfigma** [comment]
We've seen a similar stack trace in a load test:
```
github.com/jackc/chunkreader/v2.(*ChunkReader).Next(0xc0030f0000, 0x5)
        /Users/-/go/pkg/mod/github.com/jackc/chunkreader/v2@v2.0.1/chunkreader.go:61 +0x365
github.com/jackc/pgproto3/v2.(*Frontend).Receive(0xc00ca98000)
        /Users/-/go/pkg/mod/github.com/jackc/pgproto3/v2@v2.2.0/frontend.go:82 +0x129
github.com/jackc/pgconn.(*PgConn).peekMessage(0xc00caa86e0)
        /Users/-/go/pkg/mod/github.com/jackc/pgconn@v1.10.1/pgconn.go:466 +0x136
github.com/jackc/pgconn.(*PgConn).receiveMessage(0xc00caa86e0)
        /Users/-/go/pkg/mod/github.com/jackc/pgconn@v1.10.1/pgconn.go:486 +0x25
github.com/jackc/pgconn.connect({0x1342ba8, 0xc0137f6540}, 0xc00f71ee10, 0xc000277560)
        /Users/-/go/pkg/mod/github.com/jackc/pgconn@v1.10.1/pgconn.go:268 +0xa73
github.com/jackc/pgconn.ConnectConfig({0x1342ba8, 0xc0137f6540}, 0xc00f71ee10)
        /Users/-/go/pkg/mod/github.com/jackc/pgconn@v1.10.1/pgconn.go:150 +0x45d
github.com/jackc/pgx/v4.connect({0x1342ba8, 0xc0137f6540}, 0xc00f71ed20)
        /Users/-/go/pkg/mod/github.com/jackc/pgx/v4@v4.14.1/conn.go:223 +0x365
github.com/jackc/pgx/v4.Connect({0x1342ba8, 0xc0137f6540}, {0xc008a52380, 0x103c5f2})
        /Users/-/go/pkg/mod/github.com/jackc/pgx/v4@v4.14.1/conn.go:108 +0x51
```
