### ISSUE TITLE
nil pointer dereference on upgrading from 5.0.1 to 5.0.3

### ISSUE THREAD

**Issue by starudream** [jackc/pgx#1335]
**To Reproduce**

`docker run -d --name pg -e POSTGRES_PASSWORD=p1ssw0rd -p 5432:5432 postgres`

```go
package main

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/lib/pq"
)

func main() {
	conn, err := pgx.Connect(context.Background(), "postgres://postgres:p1ssw0rd@127.0.0.1:5432/postgres?sslmode=disable&default_query_exec_mode=cache_describe&timezone=Asia/Shanghai")
	if err != nil {
		panic(err)
	}
	defer conn.Close(context.Background())

	_, err = conn.Exec(context.Background(), "CREATE TABLE IF NOT EXISTS test (status SMALLINT);")
	if err != nil {
		panic(err)
	}

	rows, err := conn.Query(context.Background(), "SELECT status FROM test WHERE status = ANY($1);", pq.Array([]int16{2}))
	if err != nil {
		panic(err)
	}
	defer rows.Close()

	for rows.Next() {
		var status int
		err = rows.Scan(&status)
		if err != nil {
			panic(err)
		}
		fmt.Printf("%d\n", status)
	}
}
```

**Actual behavior**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x98 pc=0x102fa2588]

goroutine 1 [running]:
github.com/jackc/pgx/v5/pgtype.TryWrapStructEncodePlan({0x0?, 0x0})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.0.3/pgtype/pgtype.go:1803 +0x88
github.com/jackc/pgx/v5/pgtype.(*Map).PlanEncode(0xc0000d64e0, 0x15, 0x1, {0x0?, 0x0})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.0.3/pgtype/pgtype.go:1321 +0x2b8
github.com/jackc/pgx/v5/pgtype.(*ArrayCodec).PlanEncode(0xc0000c4270, 0xc0000d64e0, 0x3ed, 0x1, {0x1037df3e0, 0xc0000bbcf8})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.0.3/pgtype/array_codec.go:61 +0xa8
github.com/jackc/pgx/v5/pgtype.(*Map).PlanEncode(0xc0000d64e0, 0x3ed, 0x1, {0x1037df3e0?, 0xc0000bbcf8})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.0.3/pgtype/pgtype.go:1315 +0x220
github.com/jackc/pgx/v5/pgtype.(*Map).PlanEncode(0xc0000d64e0, 0x3ed, 0x1, {0x1036b2160?, 0xc0000bbce0})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.0.3/pgtype/pgtype.go:1322 +0x2dc
github.com/jackc/pgx/v5/pgtype.(*Map).Encode(0xc000596310?, 0xe518d?, 0xc0?, {0x1036b2160, 0xc0000bbce0}, {0xc000520a00, 0x0, 0x80})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.0.3/pgtype/pgtype.go:1973 +0x60
github.com/jackc/pgx/v5/pgtype.(*encodePlanDriverValuer).Encode(0xc000596340, {0x103805c20?, 0xc000596310}, {0xc000520a00, 0x0, 0x80})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.0.3/pgtype/pgtype.go:1398 +0x2a8
github.com/jackc/pgx/v5/pgtype.(*Map).Encode(0x103805c20?, 0x596310?, 0xc0?, {0x103805c20, 0xc000596310}, {0xc000520a00, 0x0, 0x80})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.0.3/pgtype/pgtype.go:1978 +0x84
github.com/jackc/pgx/v5.(*ExtendedQueryBuilder).encodeExtendedParamValue(0xc000452420, 0x0?, 0x299908?, 0xc0?, {0x103805c20, 0xc000596310})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.0.3/extended_query_builder.go:125 +0x11c
github.com/jackc/pgx/v5.(*ExtendedQueryBuilder).appendParam(0xc000452420, 0xc0000d64e0, 0x3ed?, 0x1, {0x103805c20?, 0xc000596310})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.0.3/extended_query_builder.go:75 +0x1e8
github.com/jackc/pgx/v5.(*ExtendedQueryBuilder).appendParam(0xc000452420, 0xc0000d64e0, 0x0?, 0xffff, {0x103805c20?, 0xc000596310})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.0.3/extended_query_builder.go:55 +0x150
github.com/jackc/pgx/v5.(*ExtendedQueryBuilder).Build(0xc000452420, 0xc0000d64e0, 0xc0000ae5f0, {0xc000596320?, 0x1, 0x1})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.0.3/extended_query_builder.go:36 +0x488
github.com/jackc/pgx/v5.(*Conn).Query(0xc000452360, {0x1038f44e8, 0xc0001b6018}, {0x103380213, 0x2f}, {0xc000596320?, 0x1, 0x1})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.0.3/conn.go:725 +0xf40
main.main()
	main.go:23 +0x208
```

**Additional context**

https://github.com/jackc/pgx/blob/11e5f68ff643f317048fb5a26ce0aa208776b845/pgtype/pgtype.go#L1803

maybe ref issue #1331

**Comment by jackc** [comment]
Fixed. But FYI, you don't need to use `pq.Array`. pgx can handle slices directly.
