### ISSUE TITLE
(linux arm-32bit) panic: unaligned 64-bit atomic operation

### ISSUE THREAD

**Issue by adonespitogo** [jackc/pgx#1465]
**Describe the bug**
Sudden panic when running in `orange pi one` linux arm (armhf).

**To Reproduce**

Create a simple instance of `pxgpool`.

```go
import(
         "os"
         "net/http"
         "fmt"
         "context"
        "github.com/jackc/pgx/v5/pgxpool"
)

func main() {
    dbpool, err := pgxpool.New(context.Background(), os.Getenv("DATABASE_URL"))
    defer dbpool.Close()
    
    http.HandleFunc("/", func(w http.ResponseWriter, _ *http.Request) {
        fmt.Fprint(w, "Hello World")
    })
    
   http.ListenAndServe(":3000", nil)
}
```

Run the code and wait for about `1 minute` and the panic will occur.

**Expected behavior**
It should not panic.

**Actual behavior**
```
panic: unaligned 64-bit atomic operation

goroutine 35 [running]:
runtime/internal/atomic.panicUnaligned()
        /opt/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Load64(0x251a7bc)
        /opt/go/src/runtime/internal/atomic/atomic_arm.s:280 +0x14
go.uber.org/atomic.(*Int64).Load(...)
        /home/pi/go/pkg/mod/go.uber.org/atomic@v1.10.0/int64.go:45
github.com/jackc/puddle/v2.(*Pool[...]).Stat(0x251a770)
        /home/pi/go/pkg/mod/github.com/jackc/puddle/v2@v2.1.2/pool.go:269 +0x74
github.com/jackc/pgx/v5/pgxpool.(*Pool).Stat(0x251a700)
        /home/pi/go/pkg/mod/github.com/jackc/pgx/v5@v5.2.0/pgxpool/pool.go:564 +0x28
github.com/jackc/pgx/v5/pgxpool.(*Pool).checkMinConns(0x251a700)
        /home/pi/go/pkg/mod/github.com/jackc/pgx/v5@v5.2.0/pgxpool/pool.go:460 +0x1c
github.com/jackc/pgx/v5/pgxpool.(*Pool).checkHealth(0x251a700)
        /home/pi/go/pkg/mod/github.com/jackc/pgx/v5@v5.2.0/pgxpool/pool.go:411 +0x1c
github.com/jackc/pgx/v5/pgxpool.(*Pool).backgroundHealthCheck(0x251a700)
        /home/pi/go/pkg/mod/github.com/jackc/pgx/v5@v5.2.0/pgxpool/pool.go:402 +0x100
github.com/jackc/pgx/v5/pgxpool.NewWithConfig.func3()
        /home/pi/go/pkg/mod/github.com/jackc/pgx/v5@v5.2.0/pgxpool/pool.go:250 +0x44
created by github.com/jackc/pgx/v5/pgxpool.NewWithConfig
        /home/pi/go/pkg/mod/github.com/jackc/pgx/v5@v5.2.0/pgxpool/pool.go:248 +0x300
make: *** [Makefile:27: serve-arm32] Error 2
```

**Version**
 - Go: `go version go1.19.4 linux/arm`
 - PostgreSQL: ` PostgreSQL 14.5 (Ubuntu 14.5-0ubuntu0.22.04.1) on arm-unknown-linux-gnueabihf, compiled by gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0, 32-bit`
 - pgx: `github.com/jackc/pgx/v5 v5.2.0`

**Comment by jackc** [comment]
Hmm... I thought that the uber atomic library was supposed to to handle alignment requirements automatically. Oh well. It was already planned to use Go 1.19 atomics when Go 1.20 is released (to comply with pgx's version policy of supporting the latest 2 versions of Go) and it definitely handles alignment.

I've committed the change to master, so you can try that now, but there won't be a tagged release until Go 1.20 is released.
