### ISSUE TITLE
runtime error on rows.Values()

### ISSUE THREAD

**Issue by jdu** [jackc/pgx#151]
Having an issue with a fairly simple query and attempting to use rows.Values()

The preface is I'm trying to set up a querying API for a few tables by building the SQL statement dynamically. The problem is I don't know the structure of the result as there are multiple tables that could be called as well as join conditions. So I need to be able to do some kind of reflection to pull the results out of `rows`.

I was setting up a simple test case of this using a basic table and a query returning 2 types (uuid, text) and poking and prodding things to see how I could set this up. 

I tried to use row.Values() and it's given me a runtime error from a panic. 

This is the code that's producing the error:

```
... everything before this is just building up sqlQuery...
    rows, err := common.ConnectionPool.Query(sqlQuery)

	if err != nil {
		log.Println(err)
	}

	defer rows.Close()

	if err != nil {
		log.Println("ERR: ",err)
	}

	rowValues, err := rows.Values()
```

The error stack is below:

```
016/06/02 23:31:51 SELECT uuid, status FROM ewars.locations LIMIT 10 OFFSET 10 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x90 pc=0x11859a]

goroutine 19 [running]:
panic(0x4a6d60, 0xc82000a0d0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/jackc/pgx.(*msgReader).readInt32(0x0, 0x20)
	/Users/jduren/Projects/ewars/src/golang/src/github.com/jackc/pgx/msg_reader.go:108 +0x2a
github.com/jackc/pgx.(*Rows).nextColumn(0xc820142dc0, 0x0, 0x2)
	/Users/jduren/Projects/ewars/src/golang/src/github.com/jackc/pgx/query.go:217 +0x176
github.com/jackc/pgx.(*Rows).Values(0xc820142dc0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/jduren/Projects/ewars/src/golang/src/github.com/jackc/pgx/query.go:334 +0x1de
service_socket/methods/query.(*Query).Execute(0x7c2870, 0xc82011eff8, 0x8, 0xc820126480, 0x2, 0x4, 0xc82011cb40, 0xc82011cba0, 0xa, 0xa, ...)
	/Users/jduren/Projects/ewars/src/golang/src/service_socket/methods/query/Query.go:69 +0x910
reflect.Value.call(0x474500, 0x488138, 0x13, 0x538190, 0x4, 0xc820193ed8, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x474500, 0x488138, 0x13, 0xc820193ed8, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
net/rpc.(*service).call(0xc82016a200, 0xc82016a100, 0xc820156058, 0xc820158280, 0xc820162180, 0x4f9bc0, 0xc82013a0c0, 0x199, 0x3c7d40, 0xc8201257a0, ...)
	/usr/local/go/src/net/rpc/server.go:383 +0x1c2
created by net/rpc.(*Server).ServeCodec
	/usr/local/go/src/net/rpc/server.go:477 +0x49d
```

**Comment by jackc** [comment]
You need to call `rows.Next()` to get the next row before `rows.Values()` to read the row values.

**Comment by jdu** [comment]
Ah, that'd do it. Was basing my code off of someone elses example for similar logic. Thanks, closing...
