### ISSUE TITLE
LRU implements Cache is Safety between coroutines？when using stmtcache

### ISSUE THREAD

**Issue by wenlive** [jackc/pgx#1626]
i got a panic info as follows，I therefore doubt whether the LRU implementation is thread safe
```
goroutine 201286 [running]:
github.com/jackc/pgconn/stmtcache.(*LRU).Get(0xc0024f1500, {0xc50478?, 0xc00003c130}, {0xc00fbf5c80, 0x16f})
	/home/wusong/go/pkg/mod/github.com/jackc/pgconn@v1.12.1/stmtcache/lru.go:64 +0x105
github.com/jackc/pgx/v4.(*Conn).Query(0xc012cd01e0, {0xc50478, 0xc00003c130}, {0xc00fbf5c80, 0x16f}, {0x0?, 0x1?, 0x4f709a?})
	/home/wusong/go/pkg/mod/github.com/jackc/pgx/v4@v4.16.1/conn.go:599 +0x6bf
github.com/crunchydata/postgresql-prometheus-adapter/pkg/postgresql.(*Client).Read(0xc000310090, 0xc01ed93cc0)
	/data/wusong/Uqbar-Prometheus-Adapter/pkg/postgresql/client.go:596 +0x85c
main.read.func1({0xc4fa10, 0xc01d98c460}, 0x4d4d37?)
	/data/wusong/Uqbar-Prometheus-Adapter/main.go:218 +0x602
net/http.HandlerFunc.ServeHTTP(0x109a540?, {0xc4fa10?, 0xc01d98c460?}, 0x6a0c96?)
	/home/wusong/go-1-19/go/src/net/http/server.go:2109 +0x2f
main.timeHandler.func1({0xc4fa10, 0xc01d98c460}, 0x43e496?)
	/data/wusong/Uqbar-Prometheus-Adapter/main.go:290 +0x8a
net/http.HandlerFunc.ServeHTTP(0xc01d98c460?, {0xc4fa10?, 0xc01d98c460?}, 0xb4ff35?)
	/home/wusong/go-1-19/go/src/net/http/server.go:2109 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0xc4fa10, 0xc01d98c460}, 0xc011774700)
	/home/wusong/go-1-19/go/src/net/http/server.go:2487 +0x149
net/http.serverHandler.ServeHTTP({0xc4ca98?}, {0xc4fa10, 0xc01d98c460}, 0xc011774700)
	/home/wusong/go-1-19/go/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc0002041e0, {0xc504e8, 0xc000310450})
	/home/wusong/go-1-19/go/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
	/home/wusong/go-1-19/go/src/net/http/server.go:3102 +0x4db
```

```
// LRU implements Cache with a Least Recently Used (LRU) cache.
type LRU struct {
	conn         *pgconn.PgConn
	mode         int
	cap          int
	prepareCount int
	m            map[string]*list.Element
	l            *list.List
	psNamePrefix string
	stmtsToClear []string
}
```
LRU uses map[string]*list.Element to store historical sql, I don't see the use of locks or channels when reading and writing m

Is it a coincidence enough that different coroutines use this connection to update stmtcache to cause this phenomenon? Or should I use different connections between different coroutines?

VERSION：
i am using v4@v4.16.1

thanks for help

**Comment by jackc** [comment]
> Is it a coincidence enough that different coroutines use this connection to update stmtcache to cause this phenomenon? Or should I use different connections between different coroutines?

From https://pkg.go.dev/github.com/jackc/pgx/v4#Conn:

> Conn is a PostgreSQL connection handle. It is not safe for concurrent usage. Use a connection pool to manage access to multiple database connections from multiple goroutines.

**Comment by wenlive** [comment]
Thanks😄
