### ISSUE TITLE
Pool triggerHealthCheck leaves stranded goroutines for 500ms

### ISSUE THREAD

**Issue by bgentry** [jackc/pgx#1641]
**Describe the bug**
After releasing all conns back to a `pgxpool.Pool` and closing the pool, there can still be goroutines left running. That's because `triggerHealthCheck` gets called upon `Release()`, and [it spawns a goroutine](https://github.com/jackc/pgx/blob/c542df4fb4cfaa8126143de5dd8c69f84a9c28cb/pgxpool/pool.go#L383C16-L393) which begins by sleeping 500ms no matter what.

This means there is no way to guarantee that a pgxpool is fully shut down with no remaining remnants, at least not without sleeping a non-trivial amount of time.

**To Reproduce**

I can try to put together a reproduction if it helps. I believe this is triggered by:

1. Running `goleak` in your program
2. Starting up a pgxpool
3. Acquiring a conn
4. Releasing the conn
5. Closing the pool
6. Observing that `goleak` sometimes detects open/leaked goroutines when the program exits.

**Expected behavior**
Closing a `pgxpool.Pool` should leave behind no remnants and no open goroutines.

**Actual behavior**
Because there is a hardcoded 500ms sleep that doesn't terminate when i.e. the pool closes sooner, goroutines are sometimes left running after the pool is closed.

**Version**
 - Go: `$ go version` -> `go version go1.20.4 darwin/amd64`
 - PostgreSQL: `$ psql --no-psqlrc --tuples-only -c 'select version()'` -> ` PostgreSQL 14.8 (Homebrew) on x86_64-apple-darwin22.4.0, compiled by Apple clang version 14.0.3 (clang-1403.0.22.14.1), 64-bit`
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` -> `github.com/jackc/pgx/v5 v5.3.1`

**Additional context**
I did not see any past issues discussing this, so I wanted to at least confirm that it was an intentional design choice and not merely an oversight or bug.

**Comment by jackc** [comment]
> Because there is a hardcoded 500ms sleep that doesn't terminate when i.e. the pool closes sooner, goroutines are sometimes left running after the pool is closed.

But the goroutine terminates after that 500ms, right? Does this behavior cause a problem?

**Comment by jackc** [comment]
🤷‍♂️ 

> This goes against the expectations a Go programmer has that when they close a resource that it is fully closed. This expectation is IMO strengthened by the [docs for Pool.Close()](https://pkg.go.dev/github.com/jackc/pgx/v5@v5.3.1/pgxpool#Pool.Close) which imply that all resources have been released by the time the method returns.

The docs say all _connections_ are closed, and they are. The fact that health checks are implemented via a background goroutine is an implementation detail that isn't exposed through the public interface.

> When using goleak in test suites to verify that no goroutines are being leaked by the code being tested, pgx generates false positives with one "leaked" goroutine per conn pool that was recently closed:

That is unfortunate, but I view it as akin to checking memory usage as soon as a value has gone out of scope. The GC may not have run yet. Once a variable is out of scope or a Pool is closed it's not visible to the user application unless runtime introspection is used.

I don't mind if someone wants to refactor / improve this, but it's not something I personally plan on working on.

**Comment by bgentry** [comment]
@jackc I opened #1642 to at least try to improve these situations, although it doesn't fully resolve the potential goleak issue. At least the workaround is documented here in case anybody goes looking for it.

If in spite of the PR you don't feel this is worth fixing, no worries, feel free to close this and the PR. Thanks for your great work on pgx regardless :v:

**Comment by mxey** [comment]
For the same reason this interacts poorly with `goleak`, it also causes issues with the new `synctest` in Go 1.25. synctest panics when goroutines are leaked, which leads to flaky tests, depending on the timing of the health checks. 

```
panic: deadlock: main bubble goroutine has exited but blocked goroutines remain [recovered, repanicked]
goroutine 53 [running]:
testing.tRunner.func1.2({0xe2a300, 0xc00021c060})
	/usr/local/go/src/testing/testing.go:1872 +0x419
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1875 +0x683
panic({0xe2a300?, 0xc00021c060?})
	/usr/local/go/src/runtime/panic.go:783 +0x132
internal/synctest.Run(0xc000490020)
	/usr/local/go/src/runtime/synctest.go:251 +0x2f4
testing/synctest.Test(0xc000003a40, 0xecaff0)
	/usr/local/go/src/testing/synctest/synctest.go:282 +0x125
gitlab.rz.babiel.com/provid/apps/cloud/cmd/controller.TestInstall(0xc000003a40)
	/src/cmd/controller/controller_test.go:29 +0x2e
testing.tRunner(0xc000003a40, 0xecade8)
	/usr/local/go/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1997 +0x9d3
goroutine 194 [sleep (durable), synctest bubble 1]:
time.Sleep(0x1dcd6500)
	/usr/local/go/src/runtime/time.go:361 +0x145
github.com/jackc/pgx/v5/pgxpool.(*Pool).triggerHealthCheck.func1()
	/var/lib/postgresql/go/pkg/mod/github.com/jackc/pgx/v5@v5.7.6/pgxpool/pool.go:464 +0x2f
created by github.com/jackc/pgx/v5/pgxpool.(*Pool).triggerHealthCheck in goroutine 66
	/var/lib/postgresql/go/pkg/mod/github.com/jackc/pgx/v5@v5.7.6/pgxpool/pool.go:461 +0x8b
```

**Comment by mxey** [comment]
@jackc I was very quite confused by this behaviour, same as the other commenter, because the documentation of Close sounds like everything is closed and released when it returns. I understand you don't see the need to change this, but could you amend the documentation for Close that background goroutines may stick around for a moment after it returns?

**Comment by jackc** [comment]
Hmmm... perhaps I was wrong and something should be done about this after all.

I'm not sure whether #1642 should be revived or a fresh PR created at this point.

**Comment by bgentry** [comment]
@jackc I’m happy to revive it if you’re ok with the general approach, or if you want to give specific feedback on how you’d prefer it to work. I too got hit by this in CI a few times recently and would love to see it fixed 🙂

**Comment by jackc** [comment]
@bgentry As far as I can see the approach is sound. Only thing I'm concerned about is the increase complexity due to needing to synchronize with channels. But is seems inevitable if this issue is to be resolved.

I reopened the PR.

**Comment by bgentry** [comment]
Should be closed now by #1642 ✌🏻
