### ISSUE TITLE
tx.SendBatch with no unprepared statements and automatic statement cache disabled causes panic

### ISSUE THREAD

**Issue by tj-alomoves** [jackc/pgx#856]
It is not necessary to initialize `stmtCache` in `conn.go` `SendBatch` when there are no unprepared statements, and doing so causes a panic if all the statements in the batch have been explicitly prepared, as `len(distinctUnpreparedQueries)` is 0 which is not an allowed capacity for a stmtCache.

https://github.com/jackc/pgx/blob/5f8d853b34bfa09fa9727f9122a347fa941af6f5/conn.go#L708

Suggested fix:

```go
	var stmtCache stmtcache.Cache
	if c.stmtcache != nil && c.stmtcache.Cap() >= len(distinctUnpreparedQueries) {
		stmtCache = c.stmtcache
	} else {
		stmtCache = stmtcache.New(c.pgConn, stmtcache.ModeDescribe, len(distinctUnpreparedQueries))
	}
```

becomes

```go
	var stmtCache stmtcache.Cache
	if c.stmtcache != nil && c.stmtcache.Cap() >= len(distinctUnpreparedQueries) {
		stmtCache = c.stmtcache
	} else if len(distintUnpreparedQueries) > 0 {
		stmtCache = stmtcache.New(c.pgConn, stmtcache.ModeDescribe, len(distinctUnpreparedQueries))
	}
```

My workaround in the meantime is to enable statement caching, however in my particular use-case this increases complexity for no benefit.

Example stacktrace:

```
panic: cache must have cap of >= 1

goroutine 155 [running]:
github.com/jackc/pgconn/stmtcache.mustBeValidCap(...)
        /Users/timothymoore/go/pkg/mod/github.com/jackc/pgconn@v1.7.0/stmtcache/stmtcache.go:50
github.com/jackc/pgconn/stmtcache.New(0xc0005d9080, 0x1, 0x0, 0x7, 0xc000316be8)
        /Users/timothymoore/go/pkg/mod/github.com/jackc/pgconn@v1.7.0/stmtcache/stmtcache.go:37 +0x91
github.com/jackc/pgx/v4.(*Conn).SendBatch(0xc00033f680, 0x4b38880, 0xc000024058, 0xc00046a300, 0xc0005920a8, 0xc000302630)
        /Users/timothymoore/go/pkg/mod/github.com/jackc/pgx/v4@v4.9.0/conn.go:759 +0xc9c
github.com/jackc/pgx/v4.(*dbTx).SendBatch(0xc000302570, 0x4b38880, 0xc000024058, 0xc00046a300, 0x1, 0xc0005920a8)0xc0004696e0, 0x4, 0x4, 0xc0000a2400, 0x4, 0x4, ...)
```

**Comment by jackc** [comment]
Thanks! Fixed.
