### ISSUE TITLE
Reliable panic on statement Close()

### ISSUE THREAD

**Issue by ribasushi** [jackc/pgx#938]
Greetings!

I am able to reliably reproduce a crash when Close()-ing an exhausted pgx.Rows. I have not yet dug into isolating it into a standalone test - it is relatively difficult given the complexity of the codepath. Opening this ticket early, in case you have ideas what's wrong / can offer guiding questions

- error
```
panic: runtime error: slice bounds out of range [:8641] with capacity 8192

goroutine 9977 [running]:
github.com/jackc/chunkreader/v2.(*ChunkReader).copyBufContents(...)
        /home/ubuntu/go/pkg/mod/github.com/jackc/chunkreader/v2@v2.0.1/chunkreader.go:101
github.com/jackc/chunkreader/v2.(*ChunkReader).Next(0xc0010d7540, 0x70c9f440, 0xc108aa82a7, 0x5, 0x1d59, 0x0, 0x0)
        /home/ubuntu/go/pkg/mod/github.com/jackc/chunkreader/v2@v2.0.1/chunkreader.go:68 +0x44d
github.com/jackc/pgproto3/v2.(*Frontend).Receive(0xc04f118c00, 0xc0c4d874c0, 0x58206f, 0xc142cc4060, 0x5ceac01)
        /home/ubuntu/go/pkg/mod/github.com/jackc/pgproto3/v2@v2.0.6/frontend.go:81 +0x63
github.com/jackc/pgconn.(*PgConn).peekMessage(0xc000578dc0, 0x0, 0x5a37a7, 0xc001626044, 0xc03bd985d8)
        /home/ubuntu/go/pkg/mod/github.com/jackc/pgconn@v1.8.0/pgconn.go:452 +0x24e
github.com/jackc/pgconn.(*PgConn).receiveMessage(0xc000578dc0, 0x100c00d66e000, 0x0, 0xc0c4d87570, 0x0)
        /home/ubuntu/go/pkg/mod/github.com/jackc/pgconn@v1.8.0/pgconn.go:470 +0x2f
github.com/jackc/pgconn.(*MultiResultReader).receiveMessage(0xc000578ed8, 0xc0c4d875f0, 0x119e9c5, 0xc01954cb00, 0x1ea419fab)
        /home/ubuntu/go/pkg/mod/github.com/jackc/pgconn@v1.8.0/pgconn.go:1301 +0x32
github.com/jackc/pgconn.(*MultiResultReader).Close(0xc000578ed8, 0x5ce1b00, 0xffffffffffffffff)
        /home/ubuntu/go/pkg/mod/github.com/jackc/pgconn@v1.8.0/pgconn.go:1365 +0x31
github.com/jackc/pgx/v4.(*batchResults).Close(0xc0196eccc0, 0xc04f9a6d08, 0xc1096598e0)
        /home/ubuntu/go/pkg/mod/github.com/jackc/pgx/v4@v4.10.1/batch.go:169 +0x267
...
```

- relevant code
```	
	...
	inserts, err := tx.Query(
		ctx,
		`INSERT INTO ... ( ... ) SELECT ... FROM ... RETURNING cid, block_ordinal`,
	)
	if err != nil  {
		return err
	}
	defer inserts.Close()
	for inserts.Next() {
		var cidBytes []byte
		var blockOrdinal *int64
		if err = inserts.Scan(&cidBytes, &blockOrdinal); err != nil {
			return err
		}
		toInsertBlockunitEntries[string(cidBytes)].bu.dbBlockOrdinal = blockOrdinal
	}

	if err = tx.Commit(ctx); err != nil {
		return err
	}
	
	// ...
	// some db-unrelated work here
	// ...

	return nil <----- the stacktrace indicates I reach here ( this is the line that "triggers" the defer() above )
```

**Comment by ribasushi** [comment]
It seems to have to do with the interleaving of `Close()` and `Commit()`. Documentation indicates `Close()` is omnipotent... should I just not use it on exhausted query-results...?

**Comment by ribasushi** [comment]
FWIW confirmed - once I removed all the Close-after-commit it stopped crashing. Downside is that the code is really difficult to follow.

**Comment by jackc** [comment]
Your stack trace shows that the problem is occurring inside of a batch. Your code snippet doesn't have any batch operations. I think the root problem is something outside of that code snippet.

**Comment by ribasushi** [comment]
@jackc I have some batching elsewhere in the program, yes, though the stacktrace clearly and consistently points at the close originating at the code-site I pasted.
Hm... I use pgxpool: could it be that the Commit releases things back to the pool, then gets picked up by the batching code, and the Close() somehow "travels" to that other context via the reused DB handle?

**Comment by jackc** [comment]
Can you run this code with the race detector?

**Comment by jwatte** [comment]
I get a very similar crash, using CopyFrom() as the destination, not using pgxpool (but using multiple parallel connections.)

Here's the code snippet:

```
        lowerTime := fromDate
        var donecnt int64
        wg := &sync.WaitGroup{}
        //  chunk the work in parallel 30-day chunks
        for {
            upperTime, last := calcUpperTime(lowerTime, toDate)
            wg.Add(1)
            go func(ft, tt time.Time) {
                defer wg.Done()
                var offset int64
                fcn, fe := from.Connect(context.Background())
                if fe != nil {
                    panic(fe)
                }
                defer dbclose(fcn)
                tcn, te := to.Connect(context.Background())
                if te != nil {
                    panic(te)
                }
                defer dbclose(tcn)
                for {
                    rows, err = fcn.Query(context.Background(), qfmt, ft, tt, offset, BatchRowCount)
                    if err != nil {
                        panic(err)
                    }
                    var n int64
                    n, err = tcn.CopyFrom(context.Background(), pgx.Identifier{"public", tab.Name}, tab.AllColumns, rows)
                    if err != nil {
                        panic(err)
                    }
                    rows.Close()
                    if n == 0 {
                        break
                    }
                    p.Update(tab.Name, atomic.AddInt64(&donecnt, n))
                    offset += n
                    p.Log(fmt.Sprintf("%s %d/%d", tab.Name, donecnt, totalsize))
                }
            }(lowerTime, upperTime)
            lowerTime = upperTime
            if last {
                break
            }
        }
        wg.Wait()
```

Here's the stack trace:

```
panic: runtime error: slice bounds out of range [:12157] with capacity 8192

goroutine 3387 [running]:
github.com/jackc/chunkreader/v2.(*ChunkReader).copyBufContents(...)
        go/pkg/mod/github.com/jackc/chunkreader/v2@v2.0.1/chunkreader.go:101
github.com/jackc/chunkreader/v2.(*ChunkReader).Next(0xc0000d2140, 0x4503bfc, 0xc0005791f7, 0x5, 0xe09, 0x0, 0x0)
        go/pkg/mod/github.com/jackc/chunkreader/v2@v2.0.1/chunkreader.go:68 +0x44d
github.com/jackc/pgproto3/v2.(*Frontend).Receive(0xc000480c00, 0x8fe7d8, 0xc000480d08, 0x0, 0x0)
        go/pkg/mod/github.com/jackc/pgproto3/v2@v2.2.0/frontend.go:82 +0x63
github.com/jackc/pgconn.(*PgConn).peekMessage(0xc0000be000, 0x8fe7d8, 0xc000480d08, 0x0, 0x0)
        go/pkg/mod/github.com/jackc/pgconn@v1.10.1/pgconn.go:466 +0x29e
github.com/jackc/pgconn.(*PgConn).receiveMessage(0xc0000be000, 0x8fe7d8, 0xc000480d08, 0x0, 0x0)
        go/pkg/mod/github.com/jackc/pgconn@v1.10.1/pgconn.go:486 +0x32
github.com/jackc/pgconn.(*ResultReader).receiveMessage(0xc0000be098, 0x8fe7d8, 0xc000480d08, 0x0, 0x0)
        /home/jwatte/observe/code/go/pkg/mod/github.com/jackc/pgconn@v1.10.1/pgconn.go:1511 +0x765
github.com/jackc/pgconn.(*ResultReader).Close(0xc0000be098, 0xc000c46cc0, 0xc0000d8000, 0x16a, 0x23a, 0x0)
        go/pkg/mod/github.com/jackc/pgconn@v1.10.1/pgconn.go:1461 +0x4b
github.com/jackc/pgx/v4.(*connRows).Close(0xc0003f5830)
        go/pkg/mod/github.com/jackc/pgx/v4@v4.14.1/rows.go:129 +0x737
oexp/bdb.CopyTableWithDate.func1(0xc000128180, 0xc00039c6a8, 0xc000468200, 0x1ec, 0xc00007ac00, 0xc00007abf0, 0xc00015c5a0, 0x11, 0xc000303c00, 0xb, ...)
        jwatte/go/src/oexp/bdb/transfer.go:191 +0x65d
created by oexp/bdb.CopyTableWithDate
        jwatte/go/src/oexp/bdb/transfer.go:169 +0x1178
```

Unfortunately, this happens on a big database that lives in an isolated VPC where I don't have a development setup (i e, only after deployment) so I haven't run this with the race detector.

**Comment by jwatte** [comment]
Also, for completeness, the `qfmt` query being run is:

```
    qfmt := fmt.Sprintf(`select %s from %s where %q >= $1 and %q < $2 order by %s offset $3 limit $4`,
        strings.Join(tab.AllColumns, ", "), tab.Name, tab.DateColumn, tab.DateColumn, strings.Join(tab.PrimaryKey, ", "))
```

**Comment by jackc** [comment]
I noticed that both error reports include slices that are larger than the default buffer size. So possibly this condition is triggered by receiving unusually large messages.

I added this fuzz test to the chunkreader test suite to exercise that path:

```go
type randomReader struct {
	rnd *rand.Rand
	mu  sync.Mutex
}

// Read reads a random number of random bytes.
func (r *randomReader) Read(p []byte) (n int, err error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	n = r.rnd.Intn(len(p) + 1)
	return r.rnd.Read(p[:n])
}

func TestChunkReaderNextFuzz(t *testing.T) {
	rr := &randomReader{rnd: rand.New(rand.NewSource(1))}
	r, err := NewConfig(rr, Config{MinBufLen: 8192})
	if err != nil {
		t.Fatal(err)
	}

	randomSizes := rand.New(rand.NewSource(0))

	for i := 0; i < 100000; i++ {
		size := randomSizes.Intn(16384) + 1
		buf, err := r.Next(size)
		if err != nil {
			t.Fatal(err)
		}
		if len(buf) != size {
			t.Fatalf("Expected to get %v bytes but got %v bytes", size, len(buf))
		}
	}
}
```

But it passes.

Then I made another test that purposely read from the chunk reader from two goroutines in an unsafe manner:

```go
func TestChunkReaderNextRaceFuzz(t *testing.T) {
	rr := &randomReader{rnd: rand.New(rand.NewSource(1))}
	r, err := NewConfig(rr, Config{MinBufLen: 8192})
	if err != nil {
		t.Fatal(err)
	}

	var wg sync.WaitGroup

	f := func() {
		wg.Add(1)
		go func() {

			randomSizes := rand.New(rand.NewSource(0))

			for i := 0; i < 100000; i++ {
				size := randomSizes.Intn(16384) + 1
				buf, err := r.Next(size)
				if err != nil {
					t.Fatal(err)
				}
				if len(buf) != size {
					t.Fatalf("Expected to get %v bytes but got %v bytes", size, len(buf))
				}
			}
			wg.Done()
		}()
	}

	f()
	f()
	wg.Wait()

}
```

and I reliably get a very similar error to the above reports: 

```
panic: runtime error: slice bounds out of range [:15659] with capacity 8192
```

with the exact slice bounds and location of the panic varying based on the run.

I consider it quite likely that this is caused by a race condition caused by the application code using a connection from two goroutines.

**Comment by jackc** [comment]
I think I found the underlying issue and fixed it in `v4.15.0`. See #1138. Double calling `BatchResults.Close()` could cause a race condition that could manifest in a different goroutine. I've made it safe to call `BatchResults.Close()` multiple times.

**Comment by jwatte** [comment]
Double-close matches the symptoms I saw! A user will typically want to defer a close while also relying on move-next to close, resulting in double closes being common.
👍
